# Ecological niche modelling
# by Fernando Paulino and Carolina Loss
# JAN - 2025
# Fixed - SEP/2025 (consistent paths, dynamic species listing
# without the "Caimamn_gpi" typo, CBI-weighted map and standard-deviation map
# added, technique referenced from João Marcos's undergraduate thesis, advised by
# Carolina Loss, based on Hirzel et al. 2006 for CBI as a
# weighting/quality filter)

library(terra)

base_dir <- "./"  # ajuste aqui se os dados estiverem em outra pasta
models_dir <- paste0(base_dir, "output/Models Maxent/")

# Fix: instead of a fixed list (which had the "Caimamn_gpi" typo hardcoded), dynamically lists the species directories actually present under output/Models Maxent/
all_items <- list.files(models_dir, full.names = TRUE)
species_list <- basename(all_items[file.info(all_items)$isdir])

cat("Espécies/populações encontradas:", length(species_list), "\n")
print(species_list)

# ---------------------------------------------------------------------------
# Load the per-replicate evaluation metrics generated by MNE010, to
# calcular o peso de CBI por run e decidir quais runs entram no ensemble
# ---------------------------------------------------------------------------
eval_file <- paste0(base_dir, "Results New/evaluation/maxent/eval_df_completo.csv")
if (!file.exists(eval_file)) {
  stop("Não encontrei ", eval_file, " - rode o MNE010 antes deste script, ",
       "ele é necessário para calcular os pesos de CBI e filtrar runs válidas.")
}
eval_df <- read.csv(eval_file)

# ---------------------------------------------------------------------------
# Reconstruct the replicate -> run number association, reading directly from the
# folder structure on disk (MNE010 does not save the run number
# explicitly in the evaluation table, so we recover it here)
# ---------------------------------------------------------------------------
run_lookup <- data.frame(species = character(), Replica = character(), run_num = integer())
for (species in species_list) {
  species_dir <- paste0(models_dir, species, "/")
  run_dirs <- list.dirs(species_dir, recursive = FALSE)
  for (run_folder in run_dirs) {
    run_num <- as.integer(gsub(".*run_", "", run_folder))
    replicate_files <- list.files(run_folder, pattern = "_samplePredictions.csv")
    replicate_names <- sub("_samplePredictions.csv", "", replicate_files)
    if (length(replicate_names) > 0) {
      run_lookup <- rbind(run_lookup, data.frame(
        species = species, Replica = replicate_names, run_num = run_num
      ))
    }
  }
}
eval_df <- merge(eval_df, run_lookup, by = c("species", "Replica"), all.x = TRUE)

# Aggregate the 5 replicates' metrics for each run into a per-run average; this is the
# average that decides whether the whole run enters the ensemble, and the weight it carries
# no mapa ponderado por CBI
run_metrics <- aggregate(cbind(wAUC, TSS, CBI) ~ species + run_num, data = eval_df, FUN = mean)
run_metrics$run_valid <- with(run_metrics, wAUC >= 0.5 & TSS >= 0.0 & CBI >= 0.4)

cat("Resumo de runs válidas por espécie:\n")
print(aggregate(run_valid ~ species, data = run_metrics, FUN = sum))

# Fix: output goes to "Results New" (a folder separate from "Results", already used in the
# previous modelling round, to avoid mixing new and old results)
consensus_dir <- paste0(base_dir, "Results New/")
dir.create(consensus_dir, recursive = TRUE, showWarnings = FALSE)

# Loop to process each species
for (species in species_list) {

  tryCatch({

    species_dir <- paste0(models_dir, species, "/")
    run_dirs <- list.dirs(species_dir, recursive = FALSE)

    # Fix: the "!!" was an attempted rlang/dplyr unquote syntax, which subset() (a base function) does not recognise
    sp_run_metrics <- run_metrics[run_metrics$species == species, ]

    raster_list <- list()
    weights <- c()
    run_labels <- c()

    for (run in run_dirs) {
      run_num <- as.integer(gsub(".*run_", "", run))

      # Fix: only enters the ensemble (mean, weighted, SD) if the run passed the quality criteria (wAUC>=0.5, TSS>=0, CBI>=0.4), same filtering logic already used in MNE010
      run_ok <- sp_run_metrics$run_valid[sp_run_metrics$run_num == run_num]
      if (length(run_ok) == 0 || !isTRUE(run_ok)) {
        cat("Run", run_num, "de", species, "não passou nos critérios de qualidade - excluída do ensemble.\n")
        next
      }

      raster_files <- list.files(run, pattern = "\\.tif$", full.names = TRUE)
      if (length(raster_files) == 0) next

      # IMPORTANT FIX: dismo::predict() for a MaxEnt model with replicatetype='crossvalidate' does NOT write a single mean raster per run
      r_replicas <- rast(raster_files)
      r <- mean(r_replicas)

      cbi_peso <- sp_run_metrics$CBI[sp_run_metrics$run_num == run_num]

      raster_list <- c(raster_list, list(r))
      weights <- c(weights, cbi_peso)
      run_labels <- c(run_labels, run_num)
    }

    if (length(raster_list) == 0) {
      warning("Nenhuma run válida encontrada para ", species, " - pulando esta espécie.")
      next  # next funciona corretamente aqui, mesmo dentro do tryCatch (ver nota no MNE06/07)
    }

    # Fix: creates a dedicated subfolder for this species/EU inside
    # "Results New", em vez de deixar todos os .tif soltos misturados
    species_out_dir <- paste0(consensus_dir, species, "/")
    dir.create(species_out_dir, recursive = TRUE, showWarnings = FALSE)

    all_rasters <- rast(raster_list)

    # ---- Map 1: simple mean (AVG) ----
    mean_raster <- mean(all_rasters)

    # ---- Mapa 2: ponderado por CBI ----
    # Normalise the weights to sum to 1, and compute the pixel-wise weighted mean
    weights_norm <- weights / sum(weights)
    cbi_weighted <- sum(all_rasters * weights_norm)

    # ---- Map 3: standard deviation across valid runs ----
    sd_raster <- app(all_rasters, sd)

    # Save the NORMAL versions (without the elevation cut-off) first
    writeRaster(mean_raster, paste0(species_out_dir, species, "_mean.tif"), overwrite = TRUE)
    writeRaster(cbi_weighted, paste0(species_out_dir, species, "_cbi_weighted.tif"), overwrite = TRUE)
    writeRaster(sd_raster, paste0(species_out_dir, species, "_sd.tif"), overwrite = TRUE)

    cat("Concluído (normal):", species, "-", length(raster_list), "runs válidas incluídas de", length(run_dirs), "totais.\n")

    cat("Concluído:", species, "-", length(raster_list), "runs válidas incluídas de", length(run_dirs), "totais.\n")

  }, error = function(e) {
    message("Falhou ao processar ", species, ": ", conditionMessage(e))
  })
}

cat("Processamento de mapas médios/ponderados/SD (versão normal) concluído para todas as espécies/populações.\n")

# =============================================================================
# ROUTINE 2: ELEVATION CUT-OFF (>800 m excluded), runs AFTER all the
# normal maps have been generated, creating a second version with the
# "_800m" suffix, without overwriting the normal files. C. latirostris does not occur
# above approximately 800 m, so this version excludes extrapolation of the
# model into areas that are physiologically implausible for the species, even if
# the model statistically "predicts" suitability there due to spurious
# spurious correlation with other variables.
# =============================================================================
cat("\nIniciando corte por elevação (>800m) nos mapas já gerados...\n")

for (species in species_list) {

  tryCatch({

    species_out_dir <- paste0(consensus_dir, species, "/")

    elev_path <- paste0(base_dir, "output/vif/pred_vif/", species, "/elev.asc")
    if (!file.exists(elev_path)) {
      warning("Camada 'elev' não encontrada para ", species,
              " - pulando o corte de elevação para esta espécie. Caminho esperado: ", elev_path)
      next
    }
    elev_raster <- rast(elev_path)
    elev_mask <- elev_raster <= 800  # TRUE (1) onde é permitido manter o valor

    tipos_mapa <- c("mean", "cbi_weighted", "sd")

    for (tipo in tipos_mapa) {
      arquivo_normal <- paste0(species_out_dir, species, "_", tipo, ".tif")
      if (!file.exists(arquivo_normal)) {
        warning("Arquivo ", arquivo_normal, " não encontrado - pulando este mapa.")
        next
      }

      r <- rast(arquivo_normal)

      mask_ajustada <- elev_mask
      if (!compareGeom(mask_ajustada, r, stopOnError = FALSE)) {
        mask_ajustada <- resample(mask_ajustada, r, method = "near")
      }

      r_cortado <- mask(r, mask_ajustada, maskvalues = c(0, NA))

      arquivo_cortado <- paste0(species_out_dir, species, "_", tipo, "_800m.tif")
      writeRaster(r_cortado, arquivo_cortado, overwrite = TRUE)
    }

    cat("Corte por elevação concluído para", species, "\n")

  }, error = function(e) {
    message("Falhou o corte por elevação de ", species, ": ", conditionMessage(e))
  })
}

cat("\nRotina de corte por elevação (>800m) concluída. Cada espécie agora tem, em Results New/<espécie>/:\n")
cat("  - <espécie>_mean.tif / _cbi_weighted.tif / _sd.tif           (versão normal, sem corte)\n")
cat("  - <espécie>_mean_800m.tif / _cbi_weighted_800m.tif / _sd_800m.tif  (versão cortada acima de 800m)\n")
