# Ecological niche modelling - RANDOM FOREST (algorithm complementary to MaxEnt)
# by Fernando Paulino and Carolina Loss
# SEP - 2025
# Updated - SEP/2025 (base_dir paths, permutation importance and
# per-variable response curves, saved to Results New/Caiman_latirostris/)
#
# FOCUS: Article 1, Caiman_latirostris only (whole species). The 7 units
# units/aggregates are left for Article 2, in a separate script
# (MNE09b_rf_unidades.R), kept for when this project begins.
#
# Reuses the SWD files (presence + background already containing the
# extracted) generated by MNE07, and the predictors selected via
# VIF (MNE05). No earlier script needs to be rerun.

library(terra)
library(randomForest)
library(dismo)
library(enmSdmX)
library(ggplot2)

set.seed(2025)

species <- "Caiman_latirostris"
base_dir <- "./"  # ajuste aqui se os dados estiverem em outra pasta

# ---------------------------------------------------------------------------
# 1. LOAD ALREADY-PREPARED SWD DATA (same files used for MaxEnt)
# ---------------------------------------------------------------------------
xy.path <- paste0(base_dir, "output/xySWD/xySWD_", species, ".csv")
pts <- read.csv(xy.path)
pts <- pts[, 6:ncol(pts)]

env.path <- paste0(base_dir, "output/biasSWD/biasSWD_", species, ".csv")
env <- read.csv(env.path)
env <- env[, 6:ncol(env)]

colnames(pts) <- gsub("current", "", colnames(pts))
colnames(env) <- gsub("current", "", colnames(env))

p.names <- colnames(pts)

# ---------------------------------------------------------------------------
# 2. LOAD PREDICTOR RASTERS FOR SPATIAL PROJECTION
# ---------------------------------------------------------------------------
species_folder <- paste0(base_dir, "output/predictors/predmod/predmodcrop/", species, "/")
pred.files <- list.files(species_folder, pattern = '*.asc$', full.names = TRUE)
pred.all <- rast(pred.files)
pred <- subset(pred.all, p.names)

# ---------------------------------------------------------------------------
# 3. OUTPUT FOLDERS
# ---------------------------------------------------------------------------
out.base <- paste0(base_dir, "output/Models Random Forest/", species, "/")
dir.create(out.base, recursive = TRUE, showWarnings = FALSE)

eval.dir <- paste0(base_dir, "Results New/evaluation/rf/")
dir.create(eval.dir, recursive = TRUE, showWarnings = FALSE)

results_dir <- paste0(base_dir, "Results New/", species, "/")
dir.create(results_dir, recursive = TRUE, showWarnings = FALSE)

# ---------------------------------------------------------------------------
# 4. BUILD THE PRESENCE (1) / BACKGROUND (0) TABLE FOR THE MODEL
# ---------------------------------------------------------------------------
swd <- rbind(pts, env)
resp <- factor(c(rep("presence", nrow(pts)), rep("background", nrow(env))),
               levels = c("background", "presence"))

eval_df <- data.frame(species = character(), run = integer(), fold = integer(),
                       Bin.Prob = numeric(), wAUC = numeric(),
                       TSS = numeric(), CBI = numeric())

importance_df <- data.frame(run = integer(), fold = integer(),
                             variavel = character(), importancia = numeric())
curves_df <- data.frame(run = integer(), fold = integer(),
                         variavel = character(), x = numeric(), y = numeric())

n.runs <- 20
k.folds <- 5
grid.n <- 25

# Accumulate the mean rasters from each run, along with whether the run is valid (same
# quality criterion from MNE010/011), so the final RF map can be built
# (mean + SD across runs) directly in this script, without depending on MNE014
run_rasters_validos <- list()

# ---------------------------------------------------------------------------
# Function: response curve for ONE variable, holding the others fixed at the
# the training-data median
# ---------------------------------------------------------------------------
response_curve <- function(model, train.data, var.name, grid.n) {
  medianas <- sapply(train.data, median, na.rm = TRUE)
  grid.vals <- seq(min(train.data[[var.name]], na.rm = TRUE),
                    max(train.data[[var.name]], na.rm = TRUE),
                    length.out = grid.n)

  newdata <- as.data.frame(matrix(rep(medianas, grid.n), nrow = grid.n, byrow = TRUE))
  colnames(newdata) <- names(medianas)
  newdata[[var.name]] <- grid.vals

  preds <- predict(model, newdata = newdata, type = "prob")[, "presence"]
  data.frame(x = grid.vals, y = preds)
}

# ---------------------------------------------------------------------------
# Function: permutation importance (same logic natively reported by MaxEnt) -
# shuffles one variable in the test set and measures the drop in wAUC
# ---------------------------------------------------------------------------
permutation_importance <- function(model, test.pres, test.bg, baseline.wauc, var.names) {
  resultado <- data.frame(variavel = character(), importancia = numeric())
  for (v in var.names) {
    test.pres.perm <- test.pres
    test.bg.perm <- test.bg
    test.pres.perm[[v]] <- sample(test.pres.perm[[v]])
    test.bg.perm[[v]] <- sample(test.bg.perm[[v]])

    pred.pres.perm <- predict(model, newdata = test.pres.perm, type = "prob")[, "presence"]
    pred.bg.perm <- predict(model, newdata = test.bg.perm, type = "prob")[, "presence"]
    wauc.perm <- enmSdmX::evalAUC(pres = pred.pres.perm, contrast = pred.bg.perm)

    queda <- max(0, baseline.wauc - wauc.perm)
    resultado <- rbind(resultado, data.frame(variavel = v, importancia = queda))
  }
  if (sum(resultado$importancia) > 0) {
    resultado$importancia <- 100 * resultado$importancia / sum(resultado$importancia)
  }
  resultado
}

# ---------------------------------------------------------------------------
# 5. MAIN LOOP: 20 runs x 5-fold cross-validation
# ---------------------------------------------------------------------------
for (run in 1:n.runs) {

  run.dir <- paste0(out.base, "run_", run, "/")
  dir.create(run.dir, recursive = TRUE, showWarnings = FALSE)

  fold.pres <- dismo::kfold(pts, k = k.folds)
  fold.bg   <- dismo::kfold(env, k = k.folds)

  fold.preds <- vector("list", k.folds)

  for (fold in 1:k.folds) {

    train.idx.p <- fold.pres != fold
    train.idx.b <- fold.bg   != fold

    train.data <- rbind(pts[train.idx.p, , drop = FALSE],
                         env[train.idx.b, , drop = FALSE])
    train.resp <- factor(c(rep("presence", sum(train.idx.p)),
                            rep("background", sum(train.idx.b))),
                          levels = c("background", "presence"))

    test.pres <- pts[!train.idx.p, , drop = FALSE]
    test.bg   <- env[!train.idx.b, , drop = FALSE]

    n.min <- min(table(train.resp))
    rf.model <- randomForest(x = train.data, y = train.resp,
                              ntree = 1000,
                              sampsize = c(background = n.min, presence = n.min),
                              replace = TRUE)

    pred.pres <- predict(rf.model, newdata = test.pres, type = "prob")[, "presence"]
    pred.bg   <- predict(rf.model, newdata = test.bg,   type = "prob")[, "presence"]

    th.grid <- seq(0, 1, by = 0.01)
    sens.spec <- sapply(th.grid, function(th) {
      tpr <- mean(pred.pres >= th)
      tnr <- mean(pred.bg   <  th)
      tpr + tnr
    })
    best.th <- th.grid[which.max(sens.spec)]

    wauc <- enmSdmX::evalAUC(pres = pred.pres, contrast = pred.bg)
    tss  <- enmSdmX::evalTSS(pres = pred.pres, contrast = pred.bg, thresholds = best.th)
    cbi  <- enmSdmX::evalContBoyce(pres = pred.pres, contrast = pred.bg)

    eval_df <- rbind(eval_df, data.frame(species = species, run = run, fold = fold,
                                          Bin.Prob = best.th, wAUC = wauc,
                                          TSS = tss, CBI = cbi))

    # Only computes importance/curves for folds that already pass the
    # quality; same filtering logic used throughout the rest of the pipeline
    if (wauc >= 0.5 && tss >= 0.0 && cbi >= 0.4) {

      imp <- permutation_importance(rf.model, test.pres, test.bg, wauc, p.names)
      imp$run <- run
      imp$fold <- fold
      importance_df <- rbind(importance_df, imp[, c("run", "fold", "variavel", "importancia")])

      for (v in p.names) {
        curva <- response_curve(rf.model, train.data, v, grid.n)
        curva$run <- run
        curva$fold <- fold
        curva$variavel <- v
        curves_df <- rbind(curves_df, curva[, c("run", "fold", "variavel", "x", "y")])
      }
    }

    fold.preds[[fold]] <- predict(pred, rf.model, type = "prob", index = 2, na.rm = TRUE)

    print(list(run = run, fold = fold, wAUC = wauc, TSS = tss, CBI = cbi))
  }

  run.stack <- rast(fold.preds)
  run.mean <- mean(run.stack)
  writeRaster(run.mean, paste0(run.dir, species, "_prediction.tif"), overwrite = TRUE)

  # Decide whether this whole run is valid (the 5-fold average passes the
  # quality criteria), same logic used in MNE011 for MaxEnt,
  # only valid runs are included in the RF's final mean/SD map
  metricas_run <- eval_df[eval_df$run == run, ]
  run_valida <- with(metricas_run, mean(wAUC) >= 0.5 & mean(TSS) >= 0.0 & mean(CBI) >= 0.4)
  if (isTRUE(run_valida)) {
    run_rasters_validos[[length(run_rasters_validos) + 1]] <- run.mean
  }

  # Fix: besides the overall accumulated file (saved under Results New/evaluation/rf/), also saves this run's specific subset inside its own run_X/ folder, keeping the same per-run organisation MaxEnt already had (each run with its own results)
  write.csv(metricas_run, paste0(run.dir, "rf_evaluation_run_", run, ".csv"), row.names = FALSE)
  importance_run <- importance_df[importance_df$run == run, ]
  curves_run <- curves_df[curves_df$run == run, ]
  write.csv(importance_run, paste0(run.dir, "rf_importance_run_", run, ".csv"), row.names = FALSE)
  write.csv(curves_run, paste0(run.dir, "rf_curves_run_", run, ".csv"), row.names = FALSE)

  write.csv(importance_df, paste0(eval.dir, "rf_importance_progresso.csv"), row.names = FALSE)
  write.csv(curves_df, paste0(eval.dir, "rf_curves_progresso.csv"), row.names = FALSE)

  print(paste0("RF concluído - run ", run, " de ", n.runs))
}

# ---------------------------------------------------------------------------
# 6. SAVE EVALUATIONS AND FILTER VALID REPLICATES (same criteria as MNE010)
# ---------------------------------------------------------------------------
write.csv(eval_df, paste0(eval.dir, "rf_evaluation_", species, ".csv"), row.names = FALSE)

eval_df$decision <- ifelse(eval_df$wAUC >= 0.5 & eval_df$TSS >= 0.0 & eval_df$CBI >= 0.4,
                            "include", "remove")
valid_replicates <- subset(eval_df, decision == "include")

if (nrow(valid_replicates) > 0) {
  metric_average <- data.frame(
    species  = species,
    Bin.Prob = mean(valid_replicates$Bin.Prob),
    wAUC     = mean(valid_replicates$wAUC),
    TSS      = mean(valid_replicates$TSS),
    CBI      = mean(valid_replicates$CBI)
  )
  write.csv(metric_average, paste0(eval.dir, "rf_validation_average_", species, ".csv"),
            row.names = FALSE)
  print("Métricas médias (RF):")
  print(metric_average)
} else {
  message("Nenhuma réplica válida (RF) encontrada para ", species, ". Verifique os critérios.")
}

# ---------------------------------------------------------------------------
# 7. IMPORTANCE SUMMARY AND RESPONSE CURVES
# ---------------------------------------------------------------------------
if (nrow(importance_df) > 0) {

  resumo_importancia <- aggregate(importancia ~ variavel, data = importance_df,
                                   FUN = function(x) c(media = mean(x), sd = sd(x)))
  resumo_importancia <- do.call(data.frame, resumo_importancia)
  colnames(resumo_importancia) <- c("variavel", "media", "sd")
  write.csv(resumo_importancia, paste0(results_dir, species, "_rf_importancia.csv"), row.names = FALSE)

  resumo_curvas <- aggregate(y ~ variavel + x, data = curves_df,
                              FUN = function(v) c(media = mean(v), sd = sd(v)))
  resumo_curvas <- do.call(data.frame, resumo_curvas)
  colnames(resumo_curvas) <- c("variavel", "x", "media", "sd")
  write.csv(resumo_curvas, paste0(results_dir, species, "_rf_curvas_resposta.csv"), row.names = FALSE)

  g_imp <- ggplot(resumo_importancia, aes(x = reorder(variavel, -media), y = media)) +
    geom_bar(stat = "identity", fill = "steelblue") +
    geom_errorbar(aes(ymin = pmax(0, media - sd), ymax = media + sd), width = 0.25) +
    labs(title = paste("Importância das Variáveis (RF) -", species),
         x = "Variável", y = "Importância (%)") +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
  ggsave(paste0(results_dir, species, "_rf_importancia.png"), g_imp, width = 10, height = 6, dpi = 300)

  g_curvas <- ggplot(resumo_curvas, aes(x = x, y = media)) +
    geom_ribbon(aes(ymin = pmax(0, media - sd), ymax = pmin(1, media + sd)), fill = "grey70", alpha = 0.5) +
    geom_line(color = "black") +
    facet_wrap(~ variavel, scales = "free_x") +
    labs(title = paste("Curvas de Resposta (RF) -", species),
         x = "Valor da variável", y = "Adequabilidade") +
    theme_minimal()
  ggsave(paste0(results_dir, species, "_rf_curvas_resposta.png"), g_curvas, width = 12, height = 8, dpi = 300)

  cat("Importância e curvas de resposta (RF) salvas em:", results_dir, "\n")
} else {
  message("Nenhuma réplica válida suficiente para calcular importância/curvas de resposta (RF).")
}

print("Processamento RF completo para Caiman_latirostris.")

# ---------------------------------------------------------------------------
# 8. RF MEAN AND SD MAP (across valid runs), with elevation cut-off
#    - same logic as MNE011, so RF is already comparable to MaxEnt in
#    Results New without depending on MNE014 running first
# ---------------------------------------------------------------------------
if (length(run_rasters_validos) > 0) {

  rf_all <- rast(run_rasters_validos)
  rf_mean <- mean(rf_all)
  rf_sd <- app(rf_all, sd)

  # Save the normal versions first
  writeRaster(rf_mean, paste0(results_dir, species, "_rf_mean.tif"), overwrite = TRUE)
  writeRaster(rf_sd, paste0(results_dir, species, "_rf_sd.tif"), overwrite = TRUE)

  cat("Mapa médio/SD do RF salvo em:", results_dir, "(", length(run_rasters_validos),
      "de", n.runs, "runs válidas)\n")

  # Elevation cut-off (>800 m excluded), same logic as MNE011/MNE014
  elev_path <- paste0(base_dir, "output/vif/pred_vif/", species, "/elev.asc")
  if (file.exists(elev_path)) {
    elev_raster <- rast(elev_path)
    elev_mask <- elev_raster <= 800

    if (!compareGeom(elev_mask, rf_mean, stopOnError = FALSE)) {
      elev_mask <- resample(elev_mask, rf_mean, method = "near")
    }

    rf_mean_800m <- mask(rf_mean, elev_mask, maskvalues = c(0, NA))
    rf_sd_800m   <- mask(rf_sd, elev_mask, maskvalues = c(0, NA))

    writeRaster(rf_mean_800m, paste0(results_dir, species, "_rf_mean_800m.tif"), overwrite = TRUE)
    writeRaster(rf_sd_800m, paste0(results_dir, species, "_rf_sd_800m.tif"), overwrite = TRUE)

    cat("Corte por elevação (>800m) do RF salvo em:", results_dir, "\n")
  } else {
    warning("Camada 'elev' não encontrada para ", species,
            " - mapas do RF salvos SEM o corte de elevação. Caminho esperado: ", elev_path)
  }

} else {
  message("Nenhuma run válida (RF) para gerar mapa médio/SD de ", species, ".")
}
