# Ecological niche modelling - CONSENSO / ENSEMBLE entre algoritmos
# by Fernando Paulino and Carolina Loss
# SEP - 2025
#
# Combines the mean maps from MaxEnt (MNE09/MNE011), Random Forest
# (MNE09b_rf_latirostris.R) and GAM (MNE09c_gam_latirostris.R) into a single
# consensus map, and reports spatial concordance among the three
# algorithms (Schoener's D, in the same spirit as ENM013b_Schoener_Hillinger,
# but comparing algorithms instead of populations).
#
# Prerequisite: the three modelling scripts (MaxEnt, RF, GAM) must already
# have been run for Caiman_latirostris.

library(terra)

species <- "Caiman_latirostris"
base_dir <- "./"  # ajuste aqui se os dados estiverem em outra pasta

# ---------------------------------------------------------------------------
# 1. HELPER FUNCTION: computes an algorithm's mean map from the runs
#    (generalises the logic from MNE011_avar_maps.R to any base_dir)
# ---------------------------------------------------------------------------
mean_map_from_runs <- function(species_dir) {
  run_dirs <- list.dirs(species_dir, recursive = FALSE)
  raster_list <- list()
  for (run in run_dirs) {
    raster_files <- list.files(run, pattern = "\\.tif$", full.names = TRUE)
    if (length(raster_files) > 0) {
      rasters <- rast(raster_files)
      raster_list <- c(raster_list, as.list(rasters))
    }
  }
  if (length(raster_list) == 0) return(NULL)
  all_rasters <- rast(raster_list)
  mean(all_rasters)
}

# ---------------------------------------------------------------------------
# 2. LOAD (OR COMPUTE) THE MEAN MAP FOR EACH ALGORITHM
# ---------------------------------------------------------------------------
# MaxEnt: reuses the *_mean.tif already generated by MNE011, if it exists;
# otherwise, computes it on the fly from the runs.
maxent_mean_path <- paste0(base_dir, "Results New/", species, "/", species, "_mean.tif")
if (file.exists(maxent_mean_path)) {
  maxent_mean <- rast(maxent_mean_path)
} else {
  maxent_mean <- mean_map_from_runs(paste0(base_dir, "output/Models Maxent/", species, "/"))
}

rf_mean <- mean_map_from_runs(paste0(base_dir, "output/Models Random Forest/", species, "/"))
gam_mean <- mean_map_from_runs(paste0(base_dir, "output/models_gam/", species, "/"))

if (is.null(maxent_mean) || is.null(rf_mean) || is.null(gam_mean)) {
  stop("Um ou mais algoritmos não têm rasters de run_X disponíveis. ",
       "Rode MNE09_sdm_corrigido.R, MNE09b_rf_latirostris.R e MNE09c_gam_latirostris.R antes.")
}

# ---------------------------------------------------------------------------
# 3. NORMALISE EACH MAP (0-1, min-max) BEFORE COMBINING
# ---------------------------------------------------------------------------
# The three algorithms already produce values between 0 and 1, but on scales with
# different distributions (MaxEnt's logistic output, RF's class probability,
# RF, binomial response for GAM). Min-max normalisation ensures none
# of the three algorithms dominates the consensus simply by having a wider value range
# (recommended practice in ensemble forecasting; Araújo & New, 2007).
normalize01 <- function(r) {
  rng <- terra::minmax(r)
  (r - rng[1]) / (rng[2] - rng[1])
}

maxent_norm <- normalize01(maxent_mean)
rf_norm     <- normalize01(rf_mean)
gam_norm    <- normalize01(gam_mean)

# ---------------------------------------------------------------------------
# 4. CONSENSUS MAP (simple mean of the three normalised algorithms)
# ---------------------------------------------------------------------------
consensus_dir <- paste0(base_dir, "Results New/", species, "/")
dir.create(consensus_dir, recursive = TRUE, showWarnings = FALSE)

consensus <- mean(c(maxent_norm, rf_norm, gam_norm))
writeRaster(consensus, paste0(consensus_dir, species, "_consensus_mean.tif"), overwrite = TRUE)

# Standard-deviation map across algorithms: shows where the three algorithms
# disagree the most (useful for discussing spatial uncertainty in the article)
algo_stack <- c(maxent_norm, rf_norm, gam_norm)
names(algo_stack) <- c("maxent", "rf", "gam")
consensus_sd <- app(algo_stack, sd)
writeRaster(consensus_sd, paste0(consensus_dir, species, "_consensus_sd.tif"), overwrite = TRUE)

# ---------------------------------------------------------------------------
# 5. SPATIAL CONCORDANCE AMONG ALGORITHMS (Schoener's D)
# ---------------------------------------------------------------------------
# Same metric used in ENM013b_Schoener_Hillinger_TODAS.R to compare
# populations, applied here to compare algorithms. D ranges from 0 (no
# overlap) to 1 (complete spatial overlap).
schoener_D <- function(r1, r2) {
  v1 <- values(r1, na.rm = TRUE)
  v2 <- values(r2, na.rm = TRUE)
  v1 <- v1 / sum(v1)  # normaliza para somar 1 (densidade de probabilidade)
  v2 <- v2 / sum(v2)
  1 - 0.5 * sum(abs(v1 - v2))
}

D_maxent_rf   <- schoener_D(maxent_norm, rf_norm)
D_maxent_gam  <- schoener_D(maxent_norm, gam_norm)
D_rf_gam      <- schoener_D(rf_norm, gam_norm)

# Pearson correlation between algorithm pairs (a complementary metric,
# more familiar to reviewers outside the niche-modelling field)
pearson_maxent_rf  <- layerCor(c(maxent_norm, rf_norm), "pearson")$correlation[1, 2]
pearson_maxent_gam <- layerCor(c(maxent_norm, gam_norm), "pearson")$correlation[1, 2]
pearson_rf_gam     <- layerCor(c(rf_norm, gam_norm), "pearson")$correlation[1, 2]

concordance <- data.frame(
  comparison = c("MaxEnt vs RF", "MaxEnt vs GAM", "RF vs GAM"),
  schoener_D = c(D_maxent_rf, D_maxent_gam, D_rf_gam),
  pearson_r  = c(pearson_maxent_rf, pearson_maxent_gam, pearson_rf_gam)
)

write.csv(concordance, paste0(consensus_dir, species, "_algorithm_concordance.csv"),
          row.names = FALSE)

print("Concordância espacial entre algoritmos:")
print(concordance)
print(paste0("Mapa de consenso salvo em: ", consensus_dir, species, "_consensus_mean.tif"))
print(paste0("Mapa de desvio-padrão (incerteza) salvo em: ", consensus_dir, species, "_consensus_sd.tif"))

# =============================================================================
# ELEVATION CUT-OFF ROUTINE (>800 m excluded), same logic as MNE011,
# running AFTER the normal maps have already been saved, generating a second
# version with the "_800m" suffix without overwriting the normal files. C.
# latirostris does not occur above approximately 800 m, so this version
# excludes model extrapolation into physiologically implausible areas.
# =============================================================================
cat("\nIniciando corte por elevação (>800m) nos mapas de consenso...\n")

elev_path <- paste0(base_dir, "output/vif/pred_vif/", species, "/elev.asc")
if (file.exists(elev_path)) {

  elev_raster <- rast(elev_path)
  elev_mask <- elev_raster <= 800  # TRUE (1) onde é permitido manter o valor

  tipos_mapa <- c("consensus_mean", "consensus_sd")

  for (tipo in tipos_mapa) {
    arquivo_normal <- paste0(consensus_dir, species, "_", tipo, ".tif")
    if (!file.exists(arquivo_normal)) {
      warning("Arquivo ", arquivo_normal, " não encontrado - pulando este mapa.")
      next
    }

    r <- rast(arquivo_normal)

    mask_ajustada <- elev_mask
    if (!compareGeom(mask_ajustada, r, stopOnError = FALSE)) {
      mask_ajustada <- resample(mask_ajustada, r, method = "near")
    }

    r_cortado <- mask(r, mask_ajustada, maskvalues = c(0, NA))

    arquivo_cortado <- paste0(consensus_dir, species, "_", tipo, "_800m.tif")
    writeRaster(r_cortado, arquivo_cortado, overwrite = TRUE)
  }

  cat("Corte por elevação concluído para os mapas de consenso de", species, "\n")
  cat("Arquivos gerados: ", species, "_consensus_mean_800m.tif e ", species, "_consensus_sd_800m.tif\n", sep = "")

} else {
  warning("Camada 'elev' não encontrada para ", species,
          " - mapas de consenso salvos SEM o corte de elevação. Caminho esperado: ", elev_path)
}
